### ISSUE TITLE
dark theme cannot work on spinbox

### ISSUE THREAD

**Issue by shinespeciall** [randrew/phantomstyle#11]
i find my spinboxes in a dialog don't render with dark theme.

**Comment by shinespeciall** [comment]
something goes run with my VPN ot there is some other reason i don't know, i cannot post the screenshot, but anyway, i find my spinboxes in a dialog don't render with dark theme.

**Comment by shinespeciall** [comment]
the result turns out to be only spinboxes in one of the Dialog existing in my program cannot render dark mode.

**Comment by shinespeciall** [comment]
![image](https://user-images.githubusercontent.com/28697038/73940415-62006780-4926-11ea-98c3-4449fd583090.png)

**Comment by randrew** [comment]
The screenshot on the front page shows that spinboxes work fine in PhantomStyle.

**Comment by randrew** [comment]
Just to be extra sure, I tested putting a spinbox, with a dark palette, into a QDialog. It's fine. It's some bug in your application code, not PhantomStyle.
![funhouse_kD5RCEsMuZ](https://user-images.githubusercontent.com/26056/74009119-e2c27080-49c5-11ea-95f4-fc1181f8b5fd.png)
