### ISSUE TITLE
QPainterpath should be included in new Qt version

### ISSUE THREAD

**Issue by shinespeciall** [randrew/phantomstyle#22]
the code can be built fine in 5.15.0 but cannot work in 5.15.2, i add one line to pass the build
https://media.discordapp.net/attachments/446336634015842314/781358258253594634/unknown.png
https://media.discordapp.net/attachments/438731875704504330/781359081247866957/unknown.png

**Comment by randrew** [comment]
Are you using an old commit? This include already exists: https://github.com/randrew/phantomstyle/blob/master/src/phantom/phantomstyle.cpp#L11

**Comment by shinespeciall** [comment]
oh, you are right, i don't understand how submodule in github work, seems it cannot keep up to date with the most recent version
