### ISSUE TITLE
QMenuBar / QMenu ignores global QFont

### ISSUE THREAD

**Issue by yeahitsjan** [randrew/phantomstyle#24]
Hi! First of all, thank you for this wonderful style. I am currently integrating it into my own application.

As I understand it, Phantom "emerged from fusion". One thing I hated most about fusion, which unfortunately also applies to phantom, and I unfortunately see it as a bug, is this:

When I try to globally set a font like in the apps main entry point:

```cpp
QApplication app(argc, argv);
[...]
app.setFont(QFont("Tahoma", 9));
```

it is recognized by all widgets (in the image theres a QLabel and a QLineEdit). EXCEPT from the QMenuBar and the QMenu's. Currently I have to tinker a workaround every time. Why is that? Why does the QMenuBar not accept the set font?

Or is this a feature rather than a bug?

Thanks a lot!
Jan
![image](https://user-images.githubusercontent.com/74990847/110032413-6620d380-7d38-11eb-9628-480fc40e675e.png)

**Comment by randrew** [comment]
This isn't something PhantomStyle controls. It's up to your platform plugin or your application code. You probably have a platform plugin that's giving different fonts to menus and dialogs. You can take a look at Qt's stuff for setting specific fonts on specific types of widgets.
