### ISSUE TITLE
Python bindings?

### ISSUE THREAD

**Issue by bindreams** [randrew/phantomstyle#25]
I would love to use this style in Python (currently in PySide2). I was wondering if python bindings for the style are on the roadmap at all.

I tried to compile python bindings myself using the guide at https://www.kdab.com/creating-python-bindings-for-qt-libraries/ but was not successful. The compilation always ended up with unreadable errors.

**Comment by randrew** [comment]
Hmm. I don't think you need to create bindings for PhantomStyle for Python. You just need to add the style plugin to your Qt installation, and set it by name when your Qt program is starting up.
