### ISSUE TITLE
Ripcord padding

### ISSUE THREAD

**Issue by DVLP** [randrew/phantomstyle#26]
Don't know where to leave this so posting here:
I don't see how to add paddings in Ripcord UI and everything is very cramped because of that
Currently
![image](https://user-images.githubusercontent.com/5261364/114950981-157abb00-9e4c-11eb-89c6-5cc3b8bfa99b.png)

Desired effect
![image](https://user-images.githubusercontent.com/5261364/114951944-48717e80-9e4d-11eb-9e78-ed90d9cd7b97.png)

More space on the left, more line height, more space between avatar/name and text

**Comment by randrew** [comment]
This is not a Ripcord support forum. Email me or ask for help in the Ripcord Discord instance or the Slack instance.
