### ISSUE TITLE
quick question regarding interference with stylesheet

### ISSUE THREAD

**Issue by JulienMaille** [randrew/phantomstyle#27]
@randrew, do you know the reason why setting a stylesheet on a QSpinBox like this `QSpinBox { border: 1px solid #0000FF; }` reverts the drawing of arrows to some weird windows style?
![image](https://user-images.githubusercontent.com/182520/120898874-2ca87e80-c62d-11eb-956a-8c705990b8e9.png)

Is there anything I can do to prevent that? Thanks in advance.

**Comment by randrew** [comment]
Does the same thing happen with QFusionStyle?

**Comment by JulienMaille** [comment]
Yes, it does

**Comment by randrew** [comment]
I think this is probably a problem with QStyleSheetStyle, then.

**Comment by JulienMaille** [comment]
As soon as we edit the stylesheet, is phantomstyle "bypassed" to let QStyleSheetStyle paint the whole widget? I suppose there's nothing I can do from phantomstyle?

**Comment by randrew** [comment]
It depends on what QStyleSheetStyle decides to do. I haven't read the code for that particular widget control.
