### ISSUE TITLE
Checkable actions with icons in menus rendered incorrectly

### ISSUE THREAD

**Issue by jcelerier** [randrew/phantomstyle#3]
See the following : 
![bug](https://user-images.githubusercontent.com/2772730/55279076-94a7ff80-5314-11e9-8e6d-4b275cd8537f.gif)

**Comment by randrew** [comment]
Do you have a stylesheet applied to that QMenu? It doesn't look like Phantom to me.

**Comment by randrew** [comment]
For reference, here's what the menus in Phantom look like by default:

![menus1](https://user-images.githubusercontent.com/26056/55280464-453fee80-5369-11e9-8dbe-3eae9f42c194.gif)

**Comment by jcelerier** [comment]
hmm yes, I didn't expect such a change from fusion. sorry for the noise !

**Comment by randrew** [comment]
@jcelerier Fusion adds quite a bit of unnecessary width to menu items (about 120 pixels if I remember correctly), so your stylesheet may have been relying on that extra padding already existing. You might just be able to add some extra padding to your stylesheet and it will work again.
